<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'CWSH_WordPressSettingsFramework' => $strauss_src . '/iconicwp/wordpress-settings-framework/wp-settings-framework.php',
);