<?php

namespace CUMULUS\Wordpress\SecurityHeaders\Actions;

\defined( 'ABSPATH' ) || exit( 'No direct access allowed.' );

abstract class AbstractActor {
	protected $settings;

	/**
	 * Filter HTTP headers generated by WP before they're sent.
	 * MUST return the headers array.
	 *
	 * @param array $headers
	 *
	 * @return array
	 */
	public function filterHeaders( $headers ) {
	}

	/**
	 * Send or overwrite additional HTTP headers.
	 */
	public function sendHeaders() {
	}

	public function getSetting( $key ) {
		if ( $this->settings ) {
			return $this->settings->getSetting( $key );
		}

		return;
	}

	public function isActive() {
		if (
			$this->settings
			&& \method_exists( $this->settings, 'isActive' )
		) {
			return $this->settings->isActive();
		}

		return false;
	}
}
